services:
  app:
    build: .
    image: lclab/litton7-internal:latest
    container_name: litton7-internal
    volumes:
      - "${DATABASES_ROOT}:/mnt/ai_data:ro"
    ports:
      - "${HOST_IP:-127.0.0.1}:8080:8000"
    environment:
      - BATCH_SIZE=${BATCH_SIZE}
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
